### ISSUE TITLE
大佬，什么时候出测试版

### ISSUE THREAD

**Issue by charli2014** [zmatsh/udpspeed#1]
大佬，不会编译go，什么时候可以出个编译好的版本。

**Comment by zmatsh** [comment]
最近在整理

**Comment by zmatsh** [comment]
java 版本的 netty 版本会先发行

**Comment by charli2014** [comment]
辛苦大佬了。

**Comment by charli2014** [comment]
大佬，go版本的计划是不是搁置了？
很期待go版本啊

**Comment by zmatsh** [comment]
最近已经开发好了一个NSS在我的项目里面，大家可以先用，go以我目前的水平，写出来 恐怕和Java 差不到哪去，感谢支持。
